### ISSUE TITLE
chocophlan database 

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [ParkinsonLab/MetaPro#1]
Hello,
I'm going through downloading the databases, and I'm having an issue with chocophlan. Mainly because the link you propose doesn't give me a unique chocophlan.fasta file but a whole collection of .ffn.m8.gz. Is it because this is not the right link, or should I extract and cat all those sequences? 
I'm also unclear on what I need to do regarding wewote db, any advise on that?
Best,
Seb

**Comment by billytaj** [comment]
Hi Seb,
1) I'll be posting changes to the database access soon.  Chocophlan.fasta is the entirety of every chocophlan entry, concatenated into a single file, then indexed by BWA.  However, depending on your hardware, this may be impossible. 
2) There's really nothing for you to do wrt wevote.  The pipeline is an automated process.  You should not need to intervene.

**Comment by billytaj** [comment]
chocophlan no longer a single large file. 
outdated issue.
