### ISSUE TITLE
--nhost tag issue

### ISSUE THREAD

**Issue by Adrian-Zet** [ParkinsonLab/MetaPro#10]
So I started my first analysis using your software. And everything went fine it reached the rRNA removal stage and I stopped it because I realized I forgot to use the --no-host tag in an analysis with no host (lake metatranscriptome).

The problems comes from when I restarted everything with the new tag, it only fills the 0_sorted_filtered folder and then it goes straight to making the rRNA removal folders in which it obviously finds no files and it stops with an error. Can anyone help, I'll try to put the error down below:

FileNotFoundError: [Errno 2] No such file or directory: '/media/data/mran/vector_read_filter/final_results/pair_1.fastq'
( I only found part of the log, it also generates the vector_read_filter)
I must mention that the 0_sorted_ from filtered reads directory is the only one with data. Before it filled all the folders in order, 0_ , 1_ ... 6_ before going to the latest stage.

**EDIT**: It seems that the program was bypassing the quality filtering step. Yet I'm pretty sure that I deleted the bypass.log before restarting the pipeline from the output folder along with the formerly generated data. I'm rerunning it now, I'll be back with updates.

**Comment by billytaj** [comment]
yes. the bypass log is a feature.  the pipe doesn't expect users to alter things upstream. 
if you forgot an option upstream, it's effectively a new analysis.
