### ISSUE TITLE
GA_BLAT stage errors

### ISSUE THREAD

**Issue by Adrian-Zet** [ParkinsonLab/MetaPro#11]
So initially, I got an error when the workflow reached the GA_BLAT stage in which it told me I didn't have the Chocophlan.fasta and the /Chochophlan_split/ databases. I downloaded them from the curated DB link provided by you and I correctly assigned them in the Config.ini.

But now I'm getting these errors:

`
Can't open /media/data/ran/GA_BLAT/data/0_blat/singletons_88_g__Hydrogenobaculum.s__Hydrogenobaculum_sp_Y04AAS1.centroids.ffn.blatout.tmp.5 to write: No space left on device
2022-03-24 09:33:29.108820 RUNNING: singletons_88_blat_g__Prevotella.s__Prevotella_multiformis.centroids.ffnd.  mem: 763.5997421875 GB
2022-03-24 09:33:29.040446 BLAT annotation for singletons_88 g__Verminephrobacter.s__Verminephrobacter_aporrectodeae.centroids.ffn
Can't open /media/data/ran/GA_BLAT/data/0_blat/singletons_88_g__Endoriftia.s__Endoriftia_persephone.centroids.ffn.blatout.tmp.2 to write: No space left on device
2022-03-24 09:33:29.154227 RUNNING: singletons_88_blat_g__Parabacteroides.s__Parabacteroides_sp_D13.centroids.ffn.  mem: 763.5995390625 GB
Can't open /media/data/ran/GA_BLAT/data/0_blat/singletons_88_g__Verminephrobacter.s__Verminephrobacter_aporrectodeae.centroids.ffn.blatout.tmp.1 to write: No space left on device
2022-03-24 09:47:54.187352 BLAT annotation for singletons_9047_ChocoPhlAn g__Bacillus.s__Bacillus_bataviensis.centroids.ffn
2022-03-24 09:47:54.233300 BLAT annotation for singletons_9047_ChocoPhlAn g__Anaeroglobus.s__Anaeroglobus_geminatus.centroids.ffn
Can't open /media/data/ran/GA_BLAT/data/0_blat/singletons_9047_ChocoPhlAn_g__Bacillus.s__Bacillus_bataviensis.centroids.ffn.blatout to write: No space left on device
Can't open /media/data/ran/GA_BLAT/data/0_blat/singletons_9047_ChocoPhlAn_g__Anaeroglobus.s__Anaeroglobus_geminatus.centroids.ffn.blatout to write: No space left on device
2022-03-24 09:47:54.279153 RUNNING: singletons_9047_ChocoPhlAn_blat_g__Yarrowia.s__Yarrowia_lipolytica.centroids.ffnob submitted.  mem: 763.60680859375 GB
2022-03-24 09:47:54.279293 job limit reached.  waiting for queue to flush
2022-03-24 09:47:54.279305 closing down processes:  80
2022-03-24 09:47:54.459902 RUNNING: singletons_9047_ChocoPhlAn_blat_g__Cronobacter.s__Cronobacter_condimenti.centroids.ffn  mem: 763.63604296875 GB
`

I am using an attached volume (attached to ::/media directory in the docker image), and I checked everything has enough space. Could it be that there is an error with the permission? And how comes the error only started appearing now in the log files (it didn't appear initially).

The GA_BLAT folder has 13Gb until now, and there are still 5 TBytes left on the partition.
Should I try to simply kill the container, and remount the volume and restart it?

**Comment by billytaj** [comment]
it's referring to the location where you have the pipeline running.
Unfortunately, using that version of chocophlan (with the organisms organized in their own file) creates a lot of garbage.  
We do have a workaround, by using the humann3 version of chocophlan, that I packaged into larger chunks here:
https://compsysbio.org/metapro_libs/chocophlan_h3_unique/

**Comment by Adrian-Zet** [comment]
Ok, so then I have  2 questions:

1. Where do I point the config.ini DNA_DB and DNA_DB_split in that case? does the DB remain the single Chocophlan.fasta? And the DB_split become the folder of the chocophlan_h3_unique/?
(Currently they are DNA_DB: %(database_path)s/ChocoPhlAn/ChocoPhlAn.fasta  DNA_DB_Split: %(database_path)s/ChocoPhlAn/ChocoPhlAn_split/)

2. Must I restart the pipeline from scratch if I replace the DNA_DB paths in the config file or can I just delete the GA_BLAT and GA_BWA folders and the text from the bypass?

**Comment by billytaj** [comment]
I'll answer (2) as (1) is an ongoing issue re: user-friendliness

(2) no: you don't have to restart the pipe from scratch. just the GA_BWA stage

as for (1): that's an artifact from an earlier iteration.  we've since depreciated the need for 2 different libraries.  However this revelation has not been reflected in the current release.  the cleanup is backlogged for the time being.

**Comment by Adrian-Zet** [comment]
So I've been trying both the chocophlan_h3_unique and the _chunks version. With the _unique I had the same problem with the (no space left on the device). While the chunked version of chocophlan gave me the following error in the GA_BLAT:

`Error: sequence name 235__B2S660__rplO|k__Bacteria.p__Proteobacteria.c__Alphaproteobacteria.o__Rhizobiales.f__Brucellaceae.g__Brucella.s__Brucella_abortus|UniRef90_B2$

Loaded 5010872570 letters in 5298041 sequences

Error: sequence name 235__B2S660__rplO|k__Bacteria.p__Proteobacteria.c__Alphaproteobacteria.o__Rhizobiales.f__Brucellaceae.g__Brucella.s__Brucella_abortus|UniRef90_B2$

Loaded 5010872570 letters in 5298041 sequences

Error: sequence name 235__B2S660__rplO|k__Bacteria.p__Proteobacteria.c__Alphaproteobacteria.o__Rhizobiales.f__Brucellaceae.g__Brucella.s__Brucella_abortus|UniRef90_B2$

Loaded 5010872570 letters in 5298041 sequences

Error: sequence name 235__B2S660__rplO|k__Bacteria.p__Proteobacteria.c__Alphaproteobacteria.o__Rhizobiales.f__Brucellaceae.g__Brucella.s__Brucella_abortus|UniRef90_B2$

Loaded 5010872570 letters in 5298041 sequences

Error: sequence name 235__B2S660__rplO|k__Bacteria.p__Proteobacteria.c__Alphaproteobacteria.o__Rhizobiales.f__Brucellaceae.g__Brucella.s__Brucella_abortus|UniRef90_B2$  $f90_B2S660|UniRef50_B2S660|471 is repeated in the database, all names must be unique.

Segmentation fault (core dumped)

Segmentation fault (core dumped)

Segmentation fault (core dumped)

Segmentation fault (core dumped)`

**Comment by billytaj** [comment]
you ran out of space in your docker machine.  you probably didn't use a bind-mounted location to run your job, and so you have space issues.  The pipe creates a lot of interim datafiles.  Something we're revisiting soon.

**Comment by Adrian-Zet** [comment]
Hey Billy, thank you for the fast answer.

I am using a bind-mount. And there should be enough space left (>5Tb left).

It seems to work fine with the chocophlan_h3_chunks, but it seems that several sequences are repeated between the chunks (see errors in last comment). Is there any solution to this? So far using the chunks vs the unique files for (each organism) got me the closest to the results.

**Comment by Adrian-Zet** [comment]
So, I managed to further the workflow by taking the files from the final step that worked and doing it manually. I just wanted to ask, if I'd be using the automatic workflow, is there a way to make the pipeline create as few files as possible (must I set a big number for chunks?) or can I make it not use the chunked approach at all?

(The server we're using has ~780 Gb of RAM).

**Comment by billytaj** [comment]
since 3.0.0, this is no longer an issue.
