### ISSUE TITLE
Metatranscriptomic sample question

### ISSUE THREAD

**Issue by azam17** [ParkinsonLab/MetaPro#13]
Hi, Found this pipeline after watching the metatranscriptomic workshop on bioinformatics.ca's channel.

Apologies if the question is not relevant or link to the software. I have a question regarding metatranscriptome sample preparation.

If i plan do a metatranscriptome sample of rice, it is suggested for me to deplete the polyA tailmaterial in the total RNA or its okay just to sequence the mRNA without having to enrich the bacterial transcript. I am just worried the dominance of the host reads will reduce the signal of the bacterial mRNA. 

if no polyA tail depletion is not necessary, whats is the raw reads that is considered enough? is 20 million reads is okay?

**Comment by billytaj** [comment]
Any non-relevant material that can be removed from your dataset will ultimately speed up your analysis.  
MetaPro does not filter or remove poly-A tails. It is assumed that the user will have done that outside of the pipeline.
