### ISSUE TITLE
metatranscriptomic data accompanied with metagenomics data analysis with MetaPro

### ISSUE THREAD

**Issue by mars188** [ParkinsonLab/MetaPro#17]
Dear MetaPro developers, 

I have metatranscriptomics data set accompanied with metagenomic data (metagenomic and metatranscriptmic data obtained from the same sample).

I read in your paper and found tutorial for metatranscriptome data analysis, however, I am not sure how to use MetaPro for metatranscriptomics combined with metagenomic data analysis or a combined analysis (metagenomics + metatranscriptomic).

Is there a tutorial available or please provide me an idea on how to use MetaPro for this purpose?

Please let me know. Thanks in advance!

**Comment by billytaj** [comment]
it's a future plan to do metagenomics, but currently, MetaPro is only set up for MetaTranscriptomics.
