### ISSUE TITLE
bwa, faidx command not found

### ISSUE THREAD

**Issue by rishidash12** [ParkinsonLab/MetaPro#19]
Based on Metapro tutorial while indexing ChocoPhlAn database for BWA and DIAMOND getting error bwa and faidx command not found.

**Comment by billylaw8** [comment]
what's the command you typed?
Sounds like the command is wrong, or docker/singularity wasn't installed correctly.
Not a MetaPro issue.

**Comment by rishidash12** [comment]
this is below command i have used 
bwa index -a bwtsw <path to chocophlan_full.fasta> - samtools faidx <path to chocophlan_full.fasta>
i put chocophlan path as well.

**Comment by billylaw8** [comment]
You're not invoking any of the docker/singularity image.  Metapro doesn't install these tools for you. We package it inside a container.

You need to use singularity/docker. Please take another look at our documentation, and perhaps the tutorial too. 

Please also consult the documentation docker/singularity provide.

**Comment by rishidash12** [comment]
Can you please guide me how to invoke because I am new to docker. I followed each step in metapro tutorial.

**Comment by billylaw8** [comment]
This level of support is beyond my capacity to provide. I suggest that you contact a more senior bioinformatician at your institution or signup for the Canadian Bioinformatics workshop https://bioinformatics.ca/
