### ISSUE TITLE
Cannot run Metapro - errors with config.ini

### ISSUE THREAD

**Issue by tmattes8** [ParkinsonLab/MetaPro#21]
Hi there, I'm having similar problems getting the pipeline to run as previously reported by a different user (issue #14 with the config.ini file). It seems like the config.ini file is being ignored, even though the pipeline output indicates the correct file (with the correct path) is being used. I replaced the default path (/project/j/jparkin/Lab_Databases) with mine (/Shared/lss_tmattes/Metapro) to no avail.

I read about using absolute paths to the config file (which I've done), and include commands to bind directories so the container knows where to look for libraries that are downloaded locally. But the output (shown below) suggests the config.ini file is not being read correctly and the python script defaults to directories from the ParkinsonLab computer, which of course won't work. 

A different user figured out how to fix essentially the same problem (issue #14), but it was not detailed in the resolved issue just how the problem was fixed. Please let me know if you have some ideas on how to make the pipeline work for me.

The command string used is shown below, as is the erroneous pipeline output, which quits after trying to read the config file. 

commands used:
`$ apptainer exec -B /Users/tmattes -B /Shared/lss_tmattes /Shared/lss_tmattes/Metapro/metapro_latest.sif python3 /pipeline/MetaPro.py -c /Shared/lss_tmattes/Metapro/config.ini -1 /Shared/lss_tmattes/34412_S1_L001_R1_001.fastq -2 /Shared/lss_tmattes/34412_S1_L001_R2_001.fastq --verbose_mode leave -o /Shared/lss_tmattes `

pipeline output:

>METAPRO metatranscriptomic analysis pipeline
=====================================
no-host: False
verbose_mode: leave
working in tutorial mode: quality
CHECKING CONFIG
USING CONFIG /Shared/lss_tmattes/Metapro/config.ini
Settings no section found, using default: genus
Settings no section found, using default: 30
Settings no section found, using default: No
Settings no section found, using default: bypass_log.txt
Settings no section found, using default: none
Settings no section found, using default: 80
Settings no section found, using default: 0.1
Settings no section found, using default: chocophlan
Settings no section found, using default: 0.01
Settings no section found, using default: 90
Settings no section found, using default: 85
Settings no section found, using default: 0.65
Settings no section found, using default: 60
Settings no section found, using default: 85
Settings no section found, using default: 0.65
Settings no section found, using default: 60
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 10
Settings no section found, using default: 50
Settings no section found, using default: 10
Settings no section found, using default: 50
Settings no section found, using default: 50
Settings no section found, using default: 50
Settings no section found, using default: 50
Settings no section found, using default: 50
Settings no section found, using default: 50
Settings no section found, using default: 50
Settings no section found, using default: 5
Settings no section found, using default: 50
Settings no section found, using default: 50
Settings no section found, using default: 5
Settings no section found, using default: 60
Settings no section found, using default: 60
Settings no section found, using default: 60
Settings no section found, using default: 60
Settings no section found, using default: 1000
Settings no section found, using default: 1000
Settings no section found, using default: 60
Settings no section found, using default: 60
Settings no section found, using default: 60
Settings no section found, using default: 60
Settings no section found, using default: 60
Settings no section found, using default: 1
Settings no section found, using default: 60
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 5
Settings no section found, using default: 10
Settings no section found, using default: 1
Settings no section found, using default: yes
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: no
Settings no section found, using default: high
Settings no section found, using default: 25000
Settings no section found, using default: 50000
Settings no section found, using default: 50000
Labels no section found, using default: quality_filter
Labels no section found, using default: host_filter
Labels no section found, using default: vector_filter
Labels no section found, using default: rRNA_filter
Labels no section found, using default: rRNA_filter_split
Labels no section found, using default: rRNA_filter_convert
Labels no section found, using default: rRNA_filter_barrnap
Labels no section found, using default: rRNA_filter_barrnap_merge
Labels no section found, using default: rRNA_filter_barrnap_pp
Labels no section found, using default: rRNA_filter_infernal
Labels no section found, using default: rRNA_filter_infernal_prep
Labels no section found, using default: rRNA_filter_splitter
Labels no section found, using default: rRNA_filter_post
Labels no section found, using default: duplicate_repopulation
Labels no section found, using default: assemble_contigs
Labels no section found, using default: destroy_contigs
Labels no section found, using default: GA_pre_scan
Labels no section found, using default: GA_split
Labels no section found, using default: GA_BWA
Labels no section found, using default: GA_BWA_pp
Labels no section found, using default: GA_BWA_merge
Labels no section found, using default: GA_BLAT
Labels no section found, using default: GA_BLAT_cleanup
Labels no section found, using default: GA_BLAT_cat
Labels no section found, using default: GA_BLAT_pp
Labels no section found, using default: GA_BLAT_merge
Labels no section found, using default: GA_DMD
Labels no section found, using default: GA_DMD_pp
Labels no section found, using default: GA_final_merge
Labels no section found, using default: taxonomic_annotation
Labels no section found, using default: enzyme_annotation
Labels no section found, using default: enzyme_annotation_detect
Labels no section found, using default: enzyme_annotation_priam
Labels no section found, using default: enzyme_annotation_priam_split
Labels no section found, using default: enzyme_annotation_priam_cat
Labels no section found, using default: enzyme_annotation_DMD
Labels no section found, using default: enzyme_annotation_pp
Labels no section found, using default: outputs
Labels no section found, using default: output_copy_gene_map
Labels no section found, using default: output_clean_ec
Labels no section found, using default: output_copy_taxa
Labels no section found, using default: output_network_generation
Labels no section found, using default: output_unique_hosts_singletons
Labels no section found, using default: output_unique_hosts_pair_1
Labels no section found, using default: output_unique_hosts_pair_2
Labels no section found, using default: output_unique_vectors_singletons
Labels no section found, using default: output_unique_vectors_pair_1
Labels no section found, using default: output_unique_vectors_pair_2
Labels no section found, using default: output_combine_hosts
Labels no section found, using default: output_per_read_scores
Labels no section found, using default: output_contig_stats
Labels no section found, using default: output_ec_heatmap
Labels no section found, using default: output_taxa_groupby
Labels no section found, using default: output_read_count
Databases no section found, using default: /project/j/jparkin/Lab_Databases/univec_core/UniVec_Core.fasta
Databases no section found, using default: /project/j/jparkin/Lab_Databases/Trimmomatic_adapters/TruSeq3-PE-2.fa
Databases no section found, using default: /project/j/jparkin/Lab_Databases/Mouse_cds/Mouse_cds.fasta
Databases no section found, using default: /project/j/jparkin/Lab_Databases/Rfam/Rfam.cm
Databases no section found, using default: /project/j/jparkin/Lab_Databases/ChocoPhlAn/ChocoPhlAn.fasta
Databases no section found, using default: /project/j/jparkin/Lab_Databases/family_llbs
Databases no section found, using default: /project/j/jparkin/Lab_Databases/nr/nr
Databases no section found, using default: /project/j/jparkin/Lab_Databases/nr/nr
Databases no section found, using default: /project/j/jparkin/Lab_Databases/accession2taxid/accession2taxid
Databases no section found, using default: /project/j/jparkin/Lab_Databases/WEVOTE_db/nodes.dmp
Databases no section found, using default: /project/j/jparkin/Lab_Databases/WEVOTE_db/names.dmp
Databases no section found, using default: /project/j/jparkin/Lab_Databases/kaiju_db/kaiju_db_nr.fmi
Databases no section found, using default: /project/j/jparkin/Lab_Databases/centrifuge_db/nt
Databases no section found, using default: /project/j/jparkin/Lab_Databases/swiss_prot_db/swiss_prot_db
Databases no section found, using default: /project/j/jparkin/Lab_Databases/swiss_prot_db/SwissProt_EC_Mapping.tsv
Databases no section found, using default: /project/j/jparkin/Lab_Databases/PRIAM_db/
Databases no section found, using default: /project/j/jparkin/Lab_Databases/DETECTv2
Databases no section found, using default: /project/j/jparkin/Lab_Databases/WEVOTE_db/
Databases no section found, using default: /project/j/jparkin/Lab_Databases/EC_pathway.txt
Databases no section found, using default: /pipeline/custom_databases/pathway_to_superpathway.csv
Databases no section found, using default: /pipeline_tools/mgm/MetaGeneMark_v1.mod
Databases no section found, using default: /pipeline/custom_databases/FREQ_EC_pairs_3_mai_2020.txt
Databases no section found, using default: /pipeline/custom_databases/taxid_trees/family_tree.tsv
Databases no section found, using default: /pipeline/custom_databases/kraken2_db
dir name: /project/j/jparkin/Lab_Databases/nr
file name: nr
/project/j/jparkin/Lab_Databases/nr/nr
file does not exists

**Comment by tmattes8** [comment]
I figured out and fixed the problem. Of course, this always happens just after you get frustrated, give up and then make a public post like this. Looking forward to seeing what the pipeline can do with my data!

**Comment by DGleason-680** [comment]
Can you please share what the issue was? I'm having the same problem and I know it's a simple fix but not sure what it is.

Thanks!

**Comment by yeolex** [comment]
> I figured out and fixed the problem. Of course, this always happens just after you get frustrated, give up and then make a public post like this. Looking forward to seeing what the pipeline can do with my data!

Hi, can you please comment on how you solved this issue? I appreciate your time.
