### ISSUE TITLE
Kaiju database: unable to retrieve all genome files

### ISSUE THREAD

**Issue by DGleason-680** [ParkinsonLab/MetaPro#22]
When preparing the Kaiju database via "/pipeline_tools/kaiju/makeDB.sh" (as outlined on the tutorial page), the full list of genome files should be 40,251 but I am only receiving 38,976.
Several files return "wget: unable to resolve host address ‘na’".
I assuming this is an issue with either the makeDB.sh or the host.

I'm wondering if this will pose a problem when running the pipeline on samples.
Are all genome files necessary to successfully run MetaPro?

**Comment by billylaw8** [comment]
This sounds like a kaiju issue. not quite a MetaPro issue. 
MetaPro does not check for database robustness.  It has no concept of whether or not a database is complete.  It will only check if certain databases have been indexed, all for the purpose of making it run.  <running well is subjective, and user + input data + database - dependent>
