### ISSUE TITLE
Clear instructions on setting up required databases for v3.0.1

### ISSUE THREAD

**Issue by m-gemmell** [ParkinsonLab/MetaPro#26]
Hello

I have tried following the instructions on the main MetaPro github and the tutorial.

Unfortunately I do not find it very clear what I need to do. Some files seems fine and others don't match what the instructions or the config.ini show.

One example is that I uncompressed the directory choco_h3_genus/genus_group. Then in the tutorial it says to concatenate m8 files into a full chocophlan fasta file that does not exist. 

Any help is appreciated and if you have any questions for me please do not hesitate to contact me.

Thanks for reading
MG

**Comment by billylaw8** [comment]
We have a library downloader script to handle the download and unpacking for v3.0.1.

The tutorial walks through the workflow manually, negating the automation.
The pipeline is automated.
