### ISSUE TITLE
bad line in nhmmer output - Fatal exception (source file ../../easel/esl_sq.c, line 231):

### ISSUE THREAD

**Issue by decoder108** [ParkinsonLab/MetaPro#28]
singularity exec -B databases/:/mnt/databases -B .:/mnt/host metapro_v3.0.1.sif python3 /pipeline/MetaPro.py -c /mnt/host/Config.ini -1 /mnt/host/forward.fastq -2 /mnt/host/reverse.fastq -o /mnt/host/out/

I am running MetaPro pipeline using singularity with all the paths and databases set but I am receiving this error after the quality filtering step:

bad line in nhmmer output - Fatal exception (source file ../../easel/esl_sq.c, line 231):

Please provide a solution to this

**Comment by billylaw8** [comment]
1) this looks like a problem in your computer, not an issue with the pipe's code. pipeline is in Python. this is a C error with nhmmer.
2) your launch line looks off. unsure if singularity actually has access to /mnt.  Please recheck your bind-mounts.
