### ISSUE TITLE
Docker container doesn't contain tutorial option

### ISSUE THREAD

**Issue by Jeltje** [ParkinsonLab/MetaPro#3]
From the Dockerfile in this github repo it looks like the docker image gets built from the developer branch, which hasn't been updated since January 2020. Is this intentional?

I pulled the image from https://hub.docker.com/r/parkinsonlab/metapro
When running `python3 /pipeline/MetaPro.py` while on the container, the `--tutorial` option does not show.
Running a docker mounted version of this git repo (master branch) _does_ show this option.

**Comment by billytaj** [comment]
hi,
no, this is not intentional. 
I recommend pulling the latest docker image from the docker hub.  
Also, as of writing, we're experiencing issues on our filehosting site and we can't share the libraries with you yet

**Comment by Jeltje** [comment]
I'm not sure what you mean by pulling the latest docker image.
At https://hub.docker.com/r/parkinsonlab/metapro/tags
parkinsonlab/metapro: latest is still listed as 'last updated 2 years ago'
That's the one I pulled earlier today.

**Comment by billytaj** [comment]
I suggest using the develop tag instead.

**Comment by billytaj** [comment]
I will be enacting a cleaner build policy as soon as we get some other items off our plate.  This software will be maintained.
