### ISSUE TITLE
Downloader can't get chocophlan_h3_chunks

### ISSUE THREAD

**Issue by Jeltje** [ParkinsonLab/MetaPro#4]
The downloader tries to get a file named
`https://compsysbio.org/metapro_libs/chocophlan_h3_chunks/chocophlan_h3_chunks.tar.gz`
but that file does not exist.

Also it would be nice to have an estimate in the README of disk space needed to download all the index files. I'm already at 143G and I haven't even started on nr...

**Comment by Jeltje** [comment]
The `chocophlan_h3_chunks.tar.gz` lives one directory up:
`https://compsysbio.org/metapro_libs/chocophlan_h3_chunks.tar.gz`

The univec download also fails:
404 Client Error: Not Found for url: https://compsysbio.org/metapro_libs/univec_core/UniVec_Core.tar.gz
Should be lowercase: `univec_core.tar.gz`

**Comment by billytaj** [comment]
thanks. it's fixed on the server end
