### ISSUE TITLE
Config.ini

### ISSUE THREAD

**Issue by Jeltje** [ParkinsonLab/MetaPro#5]
I'm attempting to create my own Config.ini based on the example in this repo, and the following aren't obvious to me:

`Host: %(database_path)s/human_cds/Human_cds.fasta` # this file was not downloaded with `lib_downloader.py` and I don't see it at https://compsysbio.org/metapro_libs/. Where do I find it?

`DNA_DB: %(database_path)s/ChocoPhlAn/ChocoPhlAn.fasta` I have `chocophlan_h3_chunks` fasta files, but they're numbered chocophlan_chunk_0.fasta, chocophlan_chunk_1.fasta, etc. How do I set DNA_DB ?

`DNA_DB_Split: %(database_path)s/ChocoPhlAn/ChocoPhlAn_split/` is now `chocophlan_h3_unique` ?

**Comment by Jeltje** [comment]
I've also never seen `%(database_path)s` as a variable name, is this correct?

**Comment by billytaj** [comment]
1) host files whatever the user wants to use. Here, we used coding sequences, but it's completely up to the user.  It should work with any fasta file. We're actually exploring the efficacy of using different files to filter for contaminants.

2) Yes, that's a variable name. The config file is parsed using Python's ConfigParser library, and this is an acceptable convention to do it.

**Comment by Jeltje** [comment]
Thanks.
Since the downloader creates every other necessary file maybe it's useful to default-download your standard recommendation (ftp://ftp.ncbi.nlm.nih.gov/pub/CCDS/current_human)? After all, adapters can also be unique to the user but you provide some anyway.

**Comment by billytaj** [comment]
noted.
