### ISSUE TITLE
Location of gm_key_64

### ISSUE THREAD

**Issue by Jeltje** [ParkinsonLab/MetaPro#6]
I have registered and downloaded the MetaGeneMark key, but where does it go?
The Config.ini file has no pointer to it, and when I run MetaPro.py without, it appears to be looking in the docker /root directory:

```
2021-11-04 18:21:49.204080 running: assemble_contigs
Spades Contig assembly
Disassembling contigs
GeneMark.hmm 400-day license.
License key "/root/.gm_key" not found.
This file is neccessary in order to use GeneMark.hmm.
mgm did not run.  look into it.  pipeline stopping here
```

**Comment by billytaj** [comment]
this keyfile goes to /home/<your username>
