### ISSUE TITLE
BWA output empty

### ISSUE THREAD

**Issue by Jeltje** [ParkinsonLab/MetaPro#8]
I looked up a single command:
`>cat /mydata/testout/GA_BWA/BWA_singletons_50_chocophlan_h3_chunk.sh`

`>&2 echo 2021-11-05 18:55:16.623196 BWA on singletons_50 | /pipeline_tools/BWA/bwa mem -t 55 /mydata/indices/chocophlan_h3_chunks/chocophlan_h3_chunks.fasta /mydata/testout/GA_BWA/data/0_read_split/singletons/singletons_50.fastq | /pipeline_tools/samtools/samtools view > /mydata/testout/GA_BWA/data/1_bwa/singletons_50_chocophlan_h3_chunk.sam && touch /mydata/testout/GA_BWA/data/jobs/singletons_50_chocophlan_h3_chunk_bwa`

When running without the pipe, I get an error:
`> /pipeline_tools/BWA/bwa mem -t 55 /mydata/indices/chocophlan_h3_chunks/chocophlan_h3_chunks.fasta /mydata/testout/GA_BWA/data/0_read_split/singletons/singletons_50.fastq`
`[E::bwa_idx_load_from_disk] fail to locate the index files`

So BWA does not recognize the indexed chocophlan chunks

**Comment by Adrian-Zet** [comment]
I got a similar error running the pipeline today:

FileNotFoundError: [Errno 2] No such file or directory: '/media/database/ChocoPhlAn/ChocoPhlAn_split/'

Any help? Is it probably due to a problem with the database script ?

**Comment by billytaj** [comment]
issue no longer present.
